config/routes.rb
Sac::Application.routes.draw do
  resources :sector_goals
  resources :coordinator_goals
  resources :global_goals
  resources :members

  
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  resources :users

  

end

app/models/sector_goal.rb
class SectorGoal < ActiveRecord::Base
	belongs_to :sector
	belongs_to :user
	validates :sector_id, presence:{message: 'Debe indicar el sector.'}
	validates :start, presence: {message: 'Debe indicar la fecha de inicio.'}
	validates :finish, presence: {message: 'Debe indicar la fecha de finalización.'}
  	validates :quantity, presence: {message: 'Debe indicar la cantidad.'}  	
  	validates :user_id, presence: {message: 'Debe indicar el usuario.'}

  	validate :greater_start

	def greater_start
  		errors.add(:start,'La fecha de inicio debe ser menor que la final.') if start.nil? || finish.nil? || self.start >= self.finish
	end

	def quantity_added
		Member.where(['sector_id = ?  AND DATE(created_at) BETWEEN ? AND ?',sector_id, start, finish]).count
	end

	def percent
		value = 0
		value = (quantity_added.to_f/quantity.to_f) * 100 if quantity > 0 && quantity_added > 0
		value = 100 if value > 100
		value
	end
end

app/controllers/sector_goals_controller.rb
class SectorGoalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_sector_goal, only: [:show, :edit, :update, :destroy]

  # GET /sector_goals
  # GET /sector_goals.json
  def index
    @sector_goals = SectorGoal.order('start').page(params[:page]).per_page(15)
  end

  # GET /sector_goals/1
  # GET /sector_goals/1.json
  def show
  end

  # GET /sector_goals/new
  def new
    @sector_goal = SectorGoal.new
  end

  # GET /sector_goals/1/edit
  def edit
  end

  # POST /sector_goals
  # POST /sector_goals.json
  def create
    @sector_goal = SectorGoal.new(sector_goal_params)
    @sector_goal.user = current_user
    respond_to do |format|
      if @sector_goal.save
        format.html { redirect_to @sector_goal, notice: 'Meta por sector creada satisfactoriamente.' }
        format.json { render action: 'show', status: :created, location: @sector_goal }
      else
        format.html { render action: 'new' }
        format.json { render json: @sector_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sector_goals/1
  # PATCH/PUT /sector_goals/1.json
  def update
    respond_to do |format|
      if @sector_goal.update(sector_goal_params)
        format.html { redirect_to @sector_goal, notice: 'Meta por sector actualizada satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sector_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sector_goals/1
  # DELETE /sector_goals/1.json
  def destroy
    @sector_goal.destroy
    respond_to do |format|
      format.html { redirect_to sector_goals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector_goal
      @sector_goal = SectorGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_goal_params
      params.require(:sector_goal).permit(:sector_id, :start, :finish, :quantity, :user_id)
    end
end

app/helpers/sector_goals_helper.rb
module SectorGoalsHelper
end

app/views/sector_goals/_form.html.haml
= simple_form_for @sector_goal do |f|
  = render partial: 'shared/errors', locals: {model: @sector_goal}
  .span10
    .span5
      = f.association :sector, collection: Sector.all, include_blank: '--Seleccione--', label: 'Sector'
      = f.input :start, required: true, placeholder: 'Fecha inicio', as: :date_time_picker, label: 'Start', input_html: {class: 'date-only'}, label: 'Fecha inicio'
      = f.input :finish,required: true, placeholder: 'Fecha finalización', as: :date_time_picker, label: 'End', input_html: {class: 'date-only'}, label:'Fecha de finalización'
      = f.input :quantity, label: 'Cantidad', placeholder: 'Cantidad'
  .span10
    .form-actions
      = f.button :submit, 'Crear nueva meta por sector', :class => 'btn btn-primary'
      = link_to 'Cancelar', sector_goals_path, :class => 'btn'

app/views/sector_goals/edit.html.haml
- model_class = SectorGoal
.page-header
  = image_tag('pin.png')
  %h2 Metas por Sector
= render :partial => "form"

app/views/sector_goals/index.html.haml
- model_class = SectorGoal
.page-header
  = image_tag('pin.png')
  %h2 Metas por Sectores
  %p.explanation 
    Estas metas se refieren a las metas establecidas para cada sector en específico.
- if can? :create, SectorGoal
  = link_to 'Crear nueva meta por sector', new_sector_goal_path, :class => 'btn btn-primary'
- if @sector_goals.empty?
  %p.no-data No has agregado ninguna meta por sector.
- else
  = will_paginate @coordinator_goals, :class => 'pagination pagination-right pull-right', previous_label: h('<'), next_label: '>'
  %table.table.table-striped
    %thead
      %tr
        %th Sector
        %th Intervalo
        %th Estado
        %th Cantidad requerida/obtenida
        %th
    %tbody
      - @sector_goals.each do |sector_goal|
        %tr
          %td= sector_goal.sector.name
          %td= "#{sector_goal.start.strftime("%d/%m/%Y")} - #{sector_goal.finish.strftime("%d/%m/%Y")}"
          - if sector_goal.percent < 50
            %td.goal_under 
              = number_to_percentage(sector_goal.percent, precision: 0)
          - elsif sector_goal.percent.between?(50,99)
            %td.goal_half 
              = number_to_percentage(sector_goal.percent, precision: 0)
          - else
            %td.goal_over 
              = number_to_percentage(sector_goal.percent, precision: 0)
          %td=  "#{number_with_delimiter(sector_goal.quantity)} / #{number_with_delimiter(sector_goal.quantity_added)}"
          %td
            .btn-group
              - if can? :read, sector_goal
                = link_to 'Ver', sector_goal_path(sector_goal), :class => 'btn btn-mini btn-primary'
              - if can? :update, sector_goal
                = link_to 'Editar', edit_sector_goal_path(sector_goal), :class => 'btn btn-mini'
              - if can? :destroy, sector_goal
                = link_to 'Eliminar', sector_goal_path(sector_goal), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro?')) }, :class => 'btn btn-mini btn-danger'

app/views/sector_goals/new.html.haml
- model_class = SectorGoal
.page-header
  = image_tag('pin.png')
  %h2 Ingresar nueva Meta por Sector
= render :partial => "form"

app/views/sector_goals/show.html.haml
- model_class = SectorGoal
.page-header
  = image_tag('pin.png')
  %h2 Metas por Sector

%p
  %strong Sector:
  %br
  = @sector_goal.sector.name
%p
  %strong Fecha inicio:
  %br
  = @sector_goal.start
%p
  %strong Fecha finalización:
  %br
  = @sector_goal.finish
%p
  %strong Cantidad:
  %br
  = @sector_goal.quantity

.form-actions
  = link_to 'Volver', sector_goals_path, :class => 'btn'
  = link_to 'Editar', edit_sector_goal_path(@sector_goal), :class => 'btn'
  = link_to 'Eliminar', sector_goal_path(@sector_goal), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro?')) }, :class => 'btn btn-danger'