config/routes.rb
Sac::Application.routes.draw do
  resources :sector_goals
  resources :coordinator_goals
  resources :global_goals
  resources :members

  
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  resources :users

  

end

app/models/global_goal.rb
class GlobalGoal < ActiveRecord::Base
	#attr_accessible :start, :finish, :status_id, :quantity, :user_id, :js_start, :js_finish
	belongs_to :user
	belongs_to :state
	validates :start, presence: {message: 'Debe indicar la fecha de inicio.'}
	validates :finish, presence: {message: 'Debe indicar la fecha de finalización.'}
  	validates :description, presence: {message: 'Debe indicar la descripción.'}
  	validates :quantity, presence: {message: 'Debe indicar la cantidad.'}  	
  	validates :user_id, presence: {message: 'Debe indicar el usuario.'}

	validate :greater_start

	def greater_start
  	errors.add(:start,'La fecha de inicio debe ser menor que la final.') if start.nil? || finish.nil? || self.start >= self.finish
	end

	def quantity_added
		Member.where(['DATE(created_at) BETWEEN ? AND ?', start, finish]).count
	end

	def percent
		value = 0
		value = (quantity_added.to_f/quantity.to_f) * 100 if quantity > 0 && quantity_added > 0
		value = 100 if value > 100
		value
	end

	#Associations
	belongs_to :status
end

app/controllers/global_goals_controller.rb
class GlobalGoalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_global_goal, only: [:show, :edit, :update, :destroy]

  # GET /global_goals
  # GET /global_goals.json
  def index
    @global_goals = GlobalGoal.order('start').page(params[:page]).per_page(15)
  end

  # GET /global_goals/1
  # GET /global_goals/1.json
  def show
  end

  # GET /global_goals/new
  def new
    @global_goal = GlobalGoal.new
  end

  # GET /global_goals/1/edit
  def edit
  end

  # POST /global_goals
  # POST /global_goals.json
  def create
    @global_goal = GlobalGoal.new(global_goal_params)
    @global_goal.user = current_user
    respond_to do |format|
      if @global_goal.save
        format.html { redirect_to @global_goal, notice: 'Meta global creada satisfactoriamente.' }
        format.json { render action: 'show', status: :created, location: @global_goal }
      else
        format.html { render action: 'new' }
        format.json { render json: @global_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /global_goals/1
  # PATCH/PUT /global_goals/1.json
  def update
    respond_to do |format|
      if @global_goal.update(global_goal_params)
        format.html { redirect_to @global_goal, notice: 'Meta global actualizada satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @global_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /global_goals/1
  # DELETE /global_goals/1.json
  def destroy
    @global_goal.destroy
    respond_to do |format|
      format.html { redirect_to global_goals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_global_goal
      @global_goal = GlobalGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def global_goal_params
      params.require(:global_goal).permit(:start, :finish, :status_id, :quantity, :description, :user_id)
    end
end

app/helpers/global_goals_helper.rb
module GlobalGoalsHelper
end

app/views/global_goals/_form.html.haml
= simple_form_for @global_goal do |f|
  = render partial: 'shared/errors', locals: {model: @global_goal}
  .span10
    .span5
      = f.input :description, required: true, label: 'Descripción de la meta', placeholder: 'Indique la descripción'
      = f.input :start, required: true, placeholder: 'Fecha inicio', as: :date_time_picker, label: 'Start', input_html: {class: 'date-only'}, label: 'Fecha inicio'
      = f.input :finish,required: true, placeholder: 'Fecha finalización', as: :date_time_picker, label: 'End', input_html: {class: 'date-only'}, label:'Fecha de finalización'
      -#= f.association :status, collection: Status.all(order: 'name'), include_blank: false
      = f.input :quantity, label: 'Cantidad', placeholder: 'Cantidad'
      -#= f.input :status_id, label: 'Estado'
      -#= f.input :user_id, label: 'Creador por'
  .span10
    .form-actions
      = f.button :submit, 'Crear nueva meta', :class => 'btn btn-primary'
      = link_to 'Cancelar', global_goals_path, :class => 'btn'

app/views/global_goals/edit.html.haml
- model_class = GlobalGoal
.page-header
  = image_tag('globe2.png')
  %h2 Editar Meta Global
= render :partial => "form"

app/views/global_goals/index.html.haml
- model_class = GlobalGoal
.page-header
  = image_tag('globe2.png')
  %h2 Metas Globales del Proyecto

  %p.explanation 
    Estas metas se refieren a las metas que abarcan el proyecto completo. Para metas más específicas, puedes agregar
    = link_to 'metas por sector', sector_goals_path
    o 
    = link_to 'metas por coordinador.', coordinator_goals_path
- if can? :create, GlobalGoal
  = link_to 'Crear nueva meta', new_global_goal_path, :class => 'btn btn-primary'
- if @global_goals.empty?
  %p.no-data No has agregado ninguna meta.
- else
  = will_paginate @coordinator_goals, :class => 'pagination pagination-right pull-right', previous_label: h('<'), next_label: '>'
  %table.table.table-striped
    %thead
      %tr
        %th Descripción
        %th Intervalo
        %th Estado
        %th Cantidad requerida/obtenida
        %th
    %tbody
      - @global_goals.each do |global_goal|
        %tr
          %td= global_goal.description
          %td= "#{global_goal.start.strftime("%d/%m/%Y")} - #{global_goal.finish.strftime("%d/%m/%Y")}"
          - if global_goal.percent < 50
            %td.goal_under 
              = number_to_percentage(global_goal.percent, precision: 0)
          - elsif global_goal.percent.between?(50,99)
            %td.goal_half 
              = number_to_percentage(global_goal.percent, precision: 0)
          - else
            %td.goal_over 
              = number_to_percentage(global_goal.percent, precision: 0)
          %td=  "#{number_with_delimiter(global_goal.quantity)} / #{number_with_delimiter(global_goal.quantity_added)}"
          %td
            .btn-group
              - if can? :read, global_goal
                = link_to 'Ver', global_goal_path(global_goal), :class => 'btn btn-mini btn-primary'
              - if can? :update, global_goal
                = link_to 'Editar', edit_global_goal_path(global_goal), :class => 'btn btn-mini'
              - if can? :destroy, global_goal
                = link_to 'Eliminar', global_goal_path(global_goal), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro?')) }, :class => 'btn btn-mini btn-danger'

app/views/global_goals/new.html.haml
- model_class = GlobalGoal
.page-header
  = image_tag('globe2.png')
  %h2 Ingreso de nueva Meta Global
= render :partial => "form"

app/views/global_goals/show.html.haml
- model_class = GlobalGoal
.page-header
  = image_tag('globe2.png')
  %h2 Metal Global

%p
  %strong Fecha inicio:
  %br
  = @global_goal.start.strftime("%d/%m/%Y")
%p
  %strong Fecha finalización:
  %br
  = @global_goal.finish.strftime("%d/%m/%Y")
%p
  %strong Estado
  %br
  = number_to_percentage(@global_goal.percent, precision: 0)
%p
  %strong Cantidad:
  %br
  = @global_goal.quantity
%p
  %strong Creada por:
  %br
  = @global_goal.user.fullname

.form-actions
  = link_to 'Volver', global_goals_path, :class => 'btn'
  = link_to 'Editar', edit_global_goal_path(@global_goal), :class => 'btn'
  = link_to 'Eliminar', global_goal_path(@global_goal), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro?')) }, :class => 'btn btn-danger'