config/routes.rb
Sac::Application.routes.draw do
  resources :sector_goals
  resources :coordinator_goals
  resources :global_goals
  resources :members

  
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  resources :users

  

end

app/models/coordinator_goal.rb
class CoordinatorGoal < ActiveRecord::Base
	belongs_to :member
	belongs_to :user
	
	validates :member_id, presence:{message: 'Debe indicar el coordinador.'}
	validates :start, presence: {message: 'Debe indicar la fecha de inicio.'}
	validates :finish, presence: {message: 'Debe indicar la fecha de finalización.'}
  	validates :quantity, presence: {message: 'Debe indicar la cantidad.'}  	
  	validates :user_id, presence: {message: 'Debe indicar el usuario.'}

  	validate :greater_start

	def greater_start
  		errors.add(:start,'La fecha de inicio debe ser menor que la final.') if start.nil? || finish.nil? || self.start >= self.finish
	end

	def quantity_added
		Member.where(['member_id = ? AND DATE(created_at) BETWEEN ? AND ?', member_id, start, finish]).count
	end

	def percent
		#result = Member.where(['member_id = ? AND DATE(created_at) BETWEEN ? AND ?', member_id, start, finish]).count
		value = 0
		value = (quantity_added.to_f/quantity.to_f) * 100 if quantity > 0 && quantity_added > 0
		value = 100 if value > 100
		value
	end
end

app/controllers/coordinator_goals_controller.rb
class CoordinatorGoalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_coordinator_goal, only: [:show, :edit, :update, :destroy]

  # GET /coordinator_goals
  # GET /coordinator_goals.json
  def index
    @coordinator_goals = []
    if current_user  
      if (current_user.has_role? :coordinador)
        @coordinator_goals = CoordinatorGoal.includes('member').where("members.email" => current_user.email).order('start').page(params[:page]).per_page(15)
      elsif (current_user.has_role? :admin)
        @coordinator_goals = CoordinatorGoal.order('start').page(params[:page]).per_page(15)
      end
    end
  end

  # GET /coordinator_goals/1
  # GET /coordinator_goals/1.json
  def show
  end

  # GET /coordinator_goals/new
  def new
    @coordinator_goal = CoordinatorGoal.new
  end

  # GET /coordinator_goals/1/edit
  def edit
  end

  # POST /coordinator_goals
  # POST /coordinator_goals.json
  def create
    @coordinator_goal = CoordinatorGoal.new(coordinator_goal_params)
    @coordinator_goal.user = current_user
    respond_to do |format|
      if @coordinator_goal.save
        format.html { redirect_to @coordinator_goal, notice: 'La meta por coordinador fue creada satisfactoriamente.' }
        format.json { render action: 'show', status: :created, location: @coordinator_goal }
      else
        format.html { render action: 'new' }
        format.json { render json: @coordinator_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinator_goals/1
  # PATCH/PUT /coordinator_goals/1.json
  def update
    respond_to do |format|
      if @coordinator_goal.update(coordinator_goal_params)
        format.html { redirect_to @coordinator_goal, notice: 'La meta por coordinador fue actualizada satisfactoriamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coordinator_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinator_goals/1
  # DELETE /coordinator_goals/1.json
  def destroy
    @coordinator_goal.destroy
    respond_to do |format|
      format.html { redirect_to coordinator_goals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator_goal
      @coordinator_goal = CoordinatorGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinator_goal_params
      params.require(:coordinator_goal).permit(:member_id, :start, :finish, :quantity, :user_id)
    end
end

app/helpers/coordinator_goals_helper.rb
module CoordinatorGoalsHelper
end

app/views/coordinator_goals/_form.html.haml
= simple_form_for @coordinator_goal do |f|
  = render partial: 'shared/errors', locals: {model: @coordinator_goal}
  .span10
    .span4
      = f.association :member, collection: Member.coordinators.map{ |l| ["#{l.name} #{l.lastname}", l.id, {:name => "#{l.name} #{l.lastname}"}] }, include_blank: '--Seleccione--', label: 'Coordinador'
      = f.input :start, required: true, placeholder: 'Fecha inicio', as: :date_time_picker, label: 'Start', input_html: {class: 'date-only'}, label: 'Fecha inicio'
      = f.input :finish,required: true, placeholder: 'Fecha finalización', as: :date_time_picker, label: 'End', input_html: {class: 'date-only'}, label:'Fecha de finalización'
      = f.input :quantity, label: 'Cantidad', placeholder: 'Cantidad'
  .span10
    .form-actions
      = f.button :submit, 'Crear nueva meta por coordinador', :class => 'btn btn-primary'
      = link_to 'Cancelar', coordinator_goals_path, :class => 'btn'

app/views/coordinator_goals/edit.html.haml
- model_class = CoordinatorGoal
.page-header
  = image_tag('coordinator.png')
  %h2 Editar Meta por Coordinador
= render :partial => "form"

app/views/coordinator_goals/index.html.haml
- model_class = CoordinatorGoal
.page-header
  = image_tag('coordinator.png')
  %h2 Metas por Coordinadores
  %p.explanation 
    Estas metas se refieren a las metas establecidas para cada coordinador en específico.
- if can? :create, CoordinatorGoal
  = link_to 'Crear nueva meta por coordinador', new_coordinator_goal_path, :class => 'btn btn-primary'
- if @coordinator_goals.empty?
  - if current_user && (current_user.has_role? :coordinador)
    %p.no-data No se te ha agregado ninguna meta.
  - else
    %p.no-data No se ha agregado ninguna meta por coordinador.
- else
  = will_paginate @coordinator_goals, :class => 'pagination pagination-right pull-right', previous_label: h('<'), next_label: '>'
  %table.table.table-striped
    %thead
      %tr
        %th Coordinador responsable
        %th Intervalo
        %th Estado
        %th Cantidad requerida/ obtenida
        %th
    %tbody
      - @coordinator_goals.each do |coordinator_goal|
        %tr
          %td= "#{coordinator_goal.member.name} #{coordinator_goal.member.lastname}"
          %td= "#{coordinator_goal.start.strftime("%d/%m/%Y")} - #{coordinator_goal.finish.strftime("%d/%m/%Y")}"
          - if coordinator_goal.percent < 50
            %td.goal_under 
              = number_to_percentage(coordinator_goal.percent, precision: 0)
          - elsif coordinator_goal.percent.between?(50,99)
            %td.goal_half 
              = number_to_percentage(coordinator_goal.percent, precision: 0)
          - else
            %td.goal_over 
              = number_to_percentage(coordinator_goal.percent, precision: 0)
          %td=  "#{number_with_delimiter(coordinator_goal.quantity)} / #{number_with_delimiter(coordinator_goal.quantity_added)}"
          %td
            .btn-group
              - if can? :read, coordinator_goal
                = link_to 'Ver', coordinator_goal_path(coordinator_goal), :class => 'btn btn-mini btn-primary'
              - if can? :update, coordinator_goal
                = link_to 'Editar', edit_coordinator_goal_path(coordinator_goal), :class => 'btn btn-mini'
              - if can? :destroy, coordinator_goal
                = link_to 'Eliminar', coordinator_goal_path(coordinator_goal), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro?')) }, :class => 'btn btn-mini btn-danger'

app/views/coordinator_goals/new.html.haml
- model_class = CoordinatorGoal
.page-header
  = image_tag('coordinator.png')
  %h2 Ingresar nueva Meta por Coordinador
= render :partial => "form"

app/views/coordinator_goals/show.html.haml
- model_class = CoordinatorGoal
.page-header
  = image_tag('coordinator.png')
  %h2 Meta por Coordinador

%p
  %strong Coordinador:
  %br
  = @coordinator_goal.member.name
%p
  %strong Fecha de inicio:
  %br
  = @coordinator_goal.start
%p
  %strong Fecha finalización:
  %br
  = @coordinator_goal.finish
%p
  %strong Cantidad:
  %br
  = @coordinator_goal.quantity

.form-actions
  = link_to 'Volver', coordinator_goals_path, :class => 'btn'
  = link_to 'Editar', edit_coordinator_goal_path(@coordinator_goal), :class => 'btn'
  = link_to 'Eliminar', coordinator_goal_path(@coordinator_goal), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro?')) }, :class => 'btn btn-danger'