config/routes.rb
Sac::Application.routes.draw do
  resources :sector_goals
  resources :coordinator_goals
  resources :global_goals
  resources :members

  
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  resources :users

  

end

app/views/layouts/_footer.html.haml
%footer
  %ul.nav.nav-pills.pull-right
    %li= link_to 'Miembros', members_path
    %li= link_to 'Metas Globales', global_goals_path
    %li= link_to 'Metas Por Sector', sector_goals_path
    %li= link_to 'Metas Por Coordinador', coordinator_goals_path
    %li= link_to 'Administración', users_path
  .desc
    %h5 Acerca de...
    %p
      Sistema Administrador de Campaña (SAC), es un sistema que sirve como soporte para el seguimiento de los esfuerzos del equipo con miras a alcanzar y mantener el posicionamiento del candidato.

app/views/layouts/_navigation.html.haml
.navbar-fixed-top
  = image_tag('banner.jpg', class:'banner')
  .navbar
    .navbar-inner
      .container
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{'data-placement' => 'top left','data-toggle' => 'tooltip', href: '#', id: 'brand', title: 'SAC. Sistema Administrador de Campaña.'}
          = image_tag('logo_sys.png', alt: 'SAC', class: 'logo-app')
        .container.nav-collapse
          %ul.nav
            - if (current_user && (current_user.has_role? :admin))
              -if mobile_device?
                %li
                  = link_to global_goals_path do
                    %i.icon-globe
                    Metas Globales
                %li
                  = link_to sector_goals_path do
                    %i.icon-map-marker
                    Metas por Sector 
                %li
                  = link_to coordinator_goals_path do
                    %i.icon-user
                    Metas por Coordinador 
              - else
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                    %i.icon-th-list
                    Metas
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to global_goals_path do
                        %i.icon-globe
                        Globales
                    %li
                      = link_to sector_goals_path do
                        %i.icon-map-marker
                        Por Sector 
                    %li
                      = link_to coordinator_goals_path do
                        %i.icon-user
                        Por Coordinador 
            - else
              %li
                = link_to coordinator_goals_path do
                  %i.icon-user
                  Mi meta                 
            %li
              = link_to members_path do
                %i.icon-user
                Miembros
            %li
              = link_to '/' do 
                %i.icon-signal
                Indicadores
            / %li
            /   = link_to 'social/show' do 
            /     %i.icon-comment
            /     Social
            -#%li= link_to 'Usuarios', users_path
          %ul.nav.pull-right
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  = "Bienvenid@, #{current_user.fullname}"
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to edit_user_registration_path do
                      %i.icon-user
                      Editar cuenta
                  - if current_user.has_role? :admin
                    %li
                      = link_to users_path do
                        %i.icon-cog
                        Panel Administración
                - if user_signed_in?
                  %li
                    = link_to destroy_user_session_path, :method=>'delete' do
                      %i.icon-remove-circle
                      Salir
            - else
              %li
                = link_to new_user_session_path do
                  %i.icon-user
                  Iniciar sesión
            -#- else
            -#  %li
            -#    = link_to 'Sign up', new_user_registration_path
:javascript
  $('#brand').tooltip()

app/views/layouts/_side_navigation.html.haml
.well.sidebar-nav
  %h3 Navegación
  %ul.nav.nav-list
    %li.nav-header Metas
    %li= link_to 'Globales', global_goals_path
    %li= link_to 'Por Sector', sector_goals_path
    %li= link_to 'Por Coordinador', coordinator_goals_path
    %li.nav-header Equipo
    -#%li= link_to 'Coordinadores', members_path(only_cood: true)
    %li= link_to 'Listado de Miembros', members_path
    %li.nav-header Reporte Miembros
    %li= link_to 'Por Coordinador', ''
    %li= link_to 'Por Sector', ''
    %li= link_to 'Por Gremio', ''
    %li.nav-header Administración
    %li= link_to 'Usuarios', users_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "SAC"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    
    = javascript_include_tag "application"



  %body
    
    = render 'layouts/navigation'

    .container.container-master
      .row
        - if current_user && (current_user.has_role? :admin)
          -#.span3
          -#  = render 'layouts/side_navigation'
          .span12
            %p.notice
            = bootstrap_flash
            = yield
        - else
          .span12
            %p.notice
            = bootstrap_flash
            = yield

    - if !mobile_device?
      = render 'layouts/footer'
    / %footer
    /   .well
    /     .span9
    /       %p Sistema de Administración de campaña (SAC), es un sistema que sirve como soporte para el seguimiento de los esfuerzos del equipo con miras a alcanzar y mantener el posicionamiento del candidato.

app/views/layouts/home.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "SAC"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    = render 'layouts/navigation'

    .container.container-master
      .row
        .span12
          = bootstrap_flash
          = yield

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=utf-8", "http-equiv" => "content-type"}/
  %title RailsWickedPdf
  = wicked_pdf_stylesheet_link_tag "application", :media => "all"
  -#= wicked_pdf_javascript_include_tag "application"
  = csrf_meta_tags

  %body{style:"background: #fff"}
    = yield